#!/usr/bin/env python3
"""Python 视觉真源 → remotion/src/theme.generated.ts（渲染端常量的唯一来源）。

**这份生成物取代的是手工副本，不是新增一层。** 在它之前，`remotion/src/theme.ts`
里的 LAYOUTS / ANIM / THEME / TYPO / FONT_STACK / MONO_STACK 全是 Python 真源的
逐字手抄，改一处要记得改另一处——仓库自己把这个代价写在了 README 与
`references/rendering.md`「版式真源」里，并由 341 行的 `test_theme_parity.py`
逐字段盯着。抄一份就会漂，盯得再紧也只是把漂移推迟到某次改动。

现在抄写这件事由本脚本做：改 Python → 跑本脚本 → 提交生成物。门禁
（`tests/test_theme_generated.py`）重新生成一遍并与仓库里的文件逐字节比对，
忘了重生成会像今天这样红。操作见 `references/rendering.md`「版式真源」。

留在 `theme.ts` 手写的是**算法**而非数据：类型标注与颜色数学（WCAG 对比度保底）。
算法没法从 Python 生成——它们要在浏览器里逐帧跑。

用法：
    python scripts/gen_theme_ts.py                 # 写 remotion/src/theme.generated.ts
    python scripts/gen_theme_ts.py --check         # 只校验是否最新（CI/门禁用）
    python scripts/gen_theme_ts.py --out 别的路径
"""
import argparse
import json
import os
import re
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _template import get_canvas, load_template  # noqa: E402
from _theme import DEFAULT_THEME, get_theme_colors, theme_bg_stops  # noqa: E402

SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(SKILL_DIR, "remotion", "src", "theme.generated.ts")
ASPECTS = ("vertical", "landscape")

HEADER = """// GENERATED by scripts/gen_theme_ts.py — 手工改动会被下一次生成覆盖。
//
// 视觉真源是 scripts/_template.py（版式/动画/排版）与 scripts/_theme.py（配色），
// 不是本文件。本文件是它们的机械投影：改视觉参数只改 Python，然后跑
// `python scripts/gen_theme_ts.py` 再提交。
// 门禁 tests/test_theme_generated.py 会重新生成一遍并与本文件逐字节比对。
"""


def _layouts(tpl, typo):
    """layout.<画幅> → LAYOUTS 的两个画幅。

    与模板的三处结构差异在这里一次收口（原来靠对拍测试逐条记住）：

    1. **横屏的缺席字段补 0**。模板只在竖屏上写 verse.bottom / title.top /
       title.maxLines / image.marginSide，横屏没有这些键（横屏标题位置由左
       文字栏 flex 居中决定、不设行数上限）。TS 侧要一套齐整的形状，0 即
       "不限/不用"，语义与模板的"不设限"同义。
    2. **image.top 由 bottomGapToVerse 换算**。模板用"图底到句流顶还差多远"
       表达同一段几何，渲染端要的是图顶的绝对 y。换算式只有这一处，替代了
       对拍测试里那条手算验算。
    3. **title.lineHeight 缺省取 typography.titleLineHeight**。模板把行高放在
       typography（跨画幅默认），横屏单独覆盖。
    """
    out = {}
    for aspect in ASPECTS:
        lay = tpl["layout"][aspect]
        _, canvas_h = get_canvas(aspect)
        verse, title, image = lay["verse"], lay["title"], lay["image"]
        out[aspect] = {
            "verse": {
                "windowHeight": verse["windowHeight"],
                "bottom": verse.get("bottom", 0),
                "clipPad": verse["clipPad"],
                "linePad": verse["linePad"],
                "lineHeight": verse["lineHeight"],
                "activeRule": verse["activeRule"],
            },
            "title": {
                "top": title.get("top", 0),
                "fontSize": title["fontSize"],
                "maxLines": title.get("maxLines", 0),
                "glow": title["glow"],
                "lineHeight": title.get("lineHeight", typo["titleLineHeight"]),
            },
            "tagline": {
                "fontSize": lay["tagline"]["fontSize"],
                "marginTop": lay["tagline"]["marginTop"],
                "lineHeight": lay["tagline"]["lineHeight"],
                "indent": lay["tagline"]["indent"],
                "tickWidth": lay["tagline"]["tickWidth"],
            },
            "image": {
                "width": image["width"],
                "height": image["height"],
                # 竖屏：图顶 = 画幅高 −（句流底 + 句流窗高 + 图高 + 图底到句流的缝）
                "top": (canvas_h - verse["bottom"] - verse["windowHeight"]
                        - image["height"] - image["bottomGapToVerse"])
                       if "bottomGapToVerse" in image else 0,
                "borderRadius": image["borderRadius"],
                "marginSide": image.get("marginSide", 0),
                "glow": image["glow"],
            },
            "subtitle": {"fontSize": lay["subtitle"]["fontSize"]},
            "progressBar": {"height": lay["progressBar"]["height"]},
            "grid": {"size": lay["grid"]["size"]},
            "ambience": dict(lay["ambience"]),
            "agenda": dict(lay["agenda"]),
        }
    return out


def _landscape_only(tpl):
    """只在横屏存在的几何（left 文字栏与标题字数降档）——单列，不塞进 LAYOUTS。

    模板把它们平铺在 layout.landscape 下（textCol / margin / title.guard*），
    渲染端收成一块是为了让"竖屏没有这些"这件事在类型上就是真的。
    """
    lay = tpl["layout"]["landscape"]
    title = lay["title"]
    return {
        "textCol": dict(lay["textCol"]),
        "margin": lay["margin"],
        "titleGuards": [
            {"chars": title["guardChars1"], "size": title["guardSize1"]},
            {"chars": title["guardChars2"], "size": title["guardSize2"]},
        ],
    }


def _anim(tpl):
    """animation 块 + canvasAmbience → ANIM。

    **不带 ease 字符串**：渲染端的缓动真源是 `easing.ts` 里的具名导出
    （组件调 power2InOut() / backOut()），ANIM 里再存一份字符串副本是"两处都
    以为自己在管"的温床——改了那串字，画面不会有任何变化。`segmentWipe` 与
    `director` 同理不进：前者只实现了 line 档（生成期 `_line_only_guard` 挡住
    其它档），后者是生成期的值（canvas_kit 烘进 SVG 属性）。

    `canvasAmbience` 在模板里是顶层键（不在 animation 块下），这里一并搬过去
    ——它原先被对拍测试当成"渲染端专属、无真源"，其实模板一直有。
    """
    anim = tpl["animation"]
    apple = anim["opening"]["apple"]
    return {
        "titleEntrance": {
            "from": anim["titleEntrance"]["from"],
            "duration": anim["titleEntrance"]["duration"],
        },
        "entranceBudget": dict(anim["entranceBudget"]),
        "imageEntrance": {
            "duration": anim["imageEntrance"]["duration"],
            "startDelay": anim["imageEntrance"]["startDelay"],
            # 模板键是 vert_y（Python 命名），渲染端统一 camelCase
            "vertY": anim["imageEntrance"]["vert_y"],
        },
        "propLine": {
            "thickness": anim["propLine"]["thickness"],
            "duration": anim["propLine"]["duration"],
            "peelFrac": anim["propLine"]["peelFrac"],
            "peelRotation": anim["propLine"]["peelRotation"],
            "peelTilt": anim["propLine"]["peelTilt"],
            "peelPerspective": anim["propLine"]["peelPerspective"],
            "peelShadeFrac": anim["propLine"]["peelShadeFrac"],
        },
        "canvasAmbience": dict(tpl["canvasAmbience"]),
        "apple": {
            "title": {k: apple["title"][k]
                      for k in ("blur", "scale", "duration")},
            "kicker": {k: apple["kicker"][k]
                       for k in ("blur", "delay", "duration")},
            "rows": {k: apple["rows"][k]
                     for k in ("delay", "duration", "stagger", "y")},
            "halo": dict(apple["halo"]),
        },
    }


_KEY = re.compile(r'^(\s*)"([A-Za-z_$][\w$]*)":', re.M)


def _unquote_keys(text):
    """把 JSON 输出的对象键还原成 TS 惯用的裸标识符。

    json.dumps 是唯一能保证"值里的引号、逗号、换行都被正确转义"的序列化器，
    但它的键也带引号，生成物读起来像 JSON 而不是 TS。这里只动**行首的键位**
    （JSON.stringify(indent=2) 一定把键放在行首缩进之后，值不会），
    所以字符串值里出现的 `"foo":` 不会被误伤。
    """
    return _KEY.sub(r"\1\2:", text)


def build_ts():
    """真源 → 生成物全文。确定性：同样输入必得同样字节（键序由构造顺序定）。"""
    tpl = load_template()
    theme = get_theme_colors(DEFAULT_THEME)
    typo = tpl["typography"]
    consts = {
        "THEME": {
            "bgGradient": theme["bg_gradient"],
            # 色标从渐变里抠（_theme.theme_bg_stops）：对比度保底按最坏一档算，
            # 少一个色标就会漏算那块底色。手抄这份列表早晚会与渐变分家。
            "bgStops": theme_bg_stops(DEFAULT_THEME),
            "gridColor": theme["grid_color"],
            "textColor": theme["text_color"],
        },
        "TYPO": {
            "titleWeight": typo["titleWeight"],
            "taglineWeight": typo["taglineWeight"],
            "titleLineHeight": typo["titleLineHeight"],
            "titleTracking": typo["titleTracking"],
        },
        "FONT_STACK": typo["fontFamily"],
        "MONO_STACK": typo["monoStack"],
        "LAYOUTS": _layouts(tpl, typo),
        "LANDSCAPE_ONLY": _landscape_only(tpl),
        "ANIM": _anim(tpl),
    }
    lines = [HEADER]
    for name, value in consts.items():
        body = _unquote_keys(json.dumps(value, ensure_ascii=False, indent=2))
        lines.append(f"export const {name} = {body};\n")
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=DEFAULT_OUT, help="生成物路径")
    ap.add_argument("--check", action="store_true",
                    help="只校验仓库里的生成物是否与真源一致，不写盘（退出码 1 = 该重生成了）")
    args = ap.parse_args(argv)
    text = build_ts()

    if args.check:
        if not os.path.isfile(args.out):
            print(f"[error] 生成物不存在: {args.out}\n"
                  f"       跑 python scripts/gen_theme_ts.py 生成", file=sys.stderr)
            return 1
        with open(args.out, encoding="utf-8") as f:
            current = f.read()
        if current != text:
            print(f"[error] {os.path.relpath(args.out, SKILL_DIR)} 与 Python 真源分家了"
                  "——改了 _template.py / _theme.py 之后跑：\n"
                  "       python scripts/gen_theme_ts.py", file=sys.stderr)
            return 1
        print(f"[ok] {os.path.relpath(args.out, SKILL_DIR)} 与真源一致")
        return 0

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"[ok] {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
