// GENERATED by scripts/gen_theme_ts.py — 手工改动会被下一次生成覆盖。
//
// 视觉真源是 scripts/_template.py（版式/动画/排版）与 scripts/_theme.py（配色），
// 不是本文件。本文件是它们的机械投影：改视觉参数只改 Python，然后跑
// `python scripts/gen_theme_ts.py` 再提交。
// 门禁 tests/test_theme_generated.py 会重新生成一遍并与本文件逐字节比对。

export const THEME = {
  bgGradient: "linear-gradient(135deg,#060709 0%,#0d0f13 45%,#080a0c 100%)",
  bgStops: [
    "#060709",
    "#0d0f13",
    "#080a0c"
  ],
  gridColor: "rgba(0,220,150,0.055)",
  textColor: "#eef2ee"
};

export const TYPO = {
  titleWeight: 900,
  taglineWeight: 600,
  titleLineHeight: 1.45,
  titleTracking: "-0.02em"
};

export const FONT_STACK = "\"Microsoft YaHei\", \"PingFang SC\", \"Noto Sans SC\", \"Noto Sans CJK SC\", \"Noto Sans CJK JP\", sans-serif";

export const MONO_STACK = "ui-monospace, \"SF Mono\", Consolas, \"Courier New\", monospace";

export const LAYOUTS = {
  vertical: {
    verse: {
      windowHeight: 280,
      bottom: 50,
      clipPad: 40,
      linePad: 5,
      lineHeight: 1.5,
      activeRule: 0.12
    },
    title: {
      top: 80,
      fontSize: 64,
      maxLines: 2,
      glow: 40,
      lineHeight: 1.45
    },
    tagline: {
      fontSize: 32,
      marginTop: 8,
      lineHeight: 1.25,
      indent: 16,
      tickWidth: 8
    },
    image: {
      width: 980,
      height: 735,
      top: 325,
      borderRadius: 12,
      marginSide: 0,
      glow: 40
    },
    subtitle: {
      fontSize: 40
    },
    progressBar: {
      height: 4
    },
    grid: {
      size: 60
    },
    ambience: {
      rx: 58,
      ry: 42,
      cx: 50,
      cy: 50,
      alpha: 15,
      edge: 72,
      agendaCx: 50,
      agendaCy: 50
    },
    agenda: {
      insetX: 72,
      insetTop: 88,
      insetBottom: 96,
      titleSize: 84,
      titleLineHeight: 1.1,
      titleMarginTop: 18,
      listMarginTop: 16,
      kickerSize: 24,
      idxSize: 30,
      idxMinWidth: 52,
      nameSize: 42,
      durSize: 26,
      rowGap: 10,
      rowPad: 20,
      verseMaxWidth: 936,
      maxRows: 7,
      nameTrim: 20,
      titleGlow: 48
    }
  },
  landscape: {
    verse: {
      windowHeight: 260,
      bottom: 0,
      clipPad: 40,
      linePad: 5,
      lineHeight: 1.45,
      activeRule: 0.12
    },
    title: {
      top: 0,
      fontSize: 62,
      maxLines: 0,
      glow: 40,
      lineHeight: 1.15
    },
    tagline: {
      fontSize: 28,
      marginTop: 16,
      lineHeight: 1.3,
      indent: 22,
      tickWidth: 8
    },
    image: {
      width: 1067,
      height: 800,
      top: 0,
      borderRadius: 12,
      marginSide: 0,
      glow: 40
    },
    subtitle: {
      fontSize: 33
    },
    progressBar: {
      height: 5
    },
    grid: {
      size: 60
    },
    ambience: {
      rx: 46,
      ry: 52,
      cx: 68,
      cy: 50,
      alpha: 13,
      edge: 70,
      agendaCx: 50,
      agendaCy: 45
    },
    agenda: {
      insetX: 96,
      insetTop: 80,
      insetBottom: 72,
      titleSize: 96,
      titleLineHeight: 1.12,
      titleMarginTop: 12,
      listMarginTop: 16,
      kickerSize: 26,
      idxSize: 34,
      idxMinWidth: 60,
      nameSize: 40,
      durSize: 24,
      rowGap: 6,
      rowPad: 8,
      verseMaxWidth: 900,
      maxRows: 7,
      nameTrim: 26,
      titleGlow: 48
    }
  }
};

export const LANDSCAPE_ONLY = {
  textCol: {
    width: 613,
    gap: 56
  },
  margin: 96,
  titleGuards: [
    {
      chars: 16,
      size: 54
    },
    {
      chars: 22,
      size: 48
    }
  ]
};

export const ANIM = {
  titleEntrance: {
    from: 0.5,
    duration: 0.5
  },
  entranceBudget: {
    minFactor: 0.45,
    normSeconds: 4.0
  },
  imageEntrance: {
    duration: 0.8,
    startDelay: 0.2,
    vertY: 40
  },
  propLine: {
    thickness: 6,
    duration: 0.4,
    peelFrac: 0.3,
    peelRotation: -4,
    peelTilt: 12,
    peelPerspective: 1000,
    peelShadeFrac: 0.08
  },
  canvasAmbience: {
    rx: 135,
    ry: 85,
    cx: 50,
    cy: 42,
    alpha: 13,
    edge: 82
  },
  apple: {
    title: {
      blur: 16,
      scale: 1.06,
      duration: 1.6
    },
    kicker: {
      blur: 8,
      delay: 0.4,
      duration: 1.2
    },
    rows: {
      delay: 0.7,
      duration: 0.7,
      stagger: 0.12,
      y: 24
    },
    halo: {
      in: 1.6,
      opacity: 0.55,
      breatheTo: 0.35,
      breatheDur: 1.2
    }
  }
};
